packages:
  - "apps/*"
  - "packages/*"

catalog:
  "@types/node": 20.16.3
  "@types/react": 18.3.3
  "@types/react-dom": 18.3.0
  "@vercel/analytics": ^1.1.1
  "@vercel/speed-insights": ^1.0.2
  "react": 18.3.1
  "react-dom": 18.3.1
  "typescript": 5.5.4
  "next": 14.2.4